name: Build PS3 Plugin

# Trigger on push or manual dispatch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git subversion wget flex bison gperf \
        python2.7 python2.7-dev python-dev-is-python2 autoconf automake texinfo pkg-config \
        zlib1g-dev libtool libgmp-dev libmpfr-dev libmpc-dev make file patch \
        libelf-dev libtool-bin libncurses5-dev libncursesw5-dev gettext bzip2 \
        gcc-multilib g++-multilib

    - name: Setup Python 2.7
      run: |
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
        sudo update-alternatives --set python /usr/bin/python2.7

    - name: Setup PS3 Development Environment
      run: |
        export PS3DEV=/usr/local/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin
        sudo mkdir -p $PS3DEV
        sudo chown $USER:$USER $PS3DEV

    - name: Install PS3 Toolchain
      run: |
        git clone https://github.com/ps3dev/ps3toolchain.git
        cd ps3toolchain
        ./toolchain.sh

    - name: Build Plugin
      run: |
        export PS3DEV=/usr/local/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin
        make clean
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ps3-plugin
        path: |
          guitar_remap.sprx
          guitar_remap.conf
