name: Test Workflow

# Trigger on push or manual dispatch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test basic functionality
      run: |
        echo "=== GitHub Actions is working! ==="
        echo "Current date: $(date)"
        echo "Running on: $(uname -a)"
        echo "User: $(whoami)"
        echo "Current directory: $(pwd)"
        
    - name: List repository contents
      run: |
        echo "=== Repository contents ==="
        ls -la
        echo ""
        echo "=== Source directory ==="
        ls -la src/ || echo "No src directory found"
        
    - name: Test simple build tools
      run: |
        echo "=== Testing basic tools ==="
        which gcc && gcc --version
        which make && make --version
        echo "✅ Basic tools work!"
        
    - name: Create test file
      run: |
        echo "=== Creating test output ==="
        echo "Hello from GitHub Actions!" > test-output.txt
        echo "Build completed at: $(date)" >> test-output.txt
        cat test-output.txt

    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: test-output.txt
