name: Build PS3 Plugin

# Trigger on push or manual dispatch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test basic functionality
      run: |
        echo "=== Basic system info ==="
        uname -a
        whoami
        pwd
        ls -la
        
    - name: Install Dependencies
      run: |
        echo "=== Installing dependencies ==="
        sudo apt-get update
        sudo apt-get install -y build-essential git wget python2.7 python2.7-dev \
        autoconf automake texinfo pkg-config zlib1g-dev libtool libgmp-dev \
        libmpfr-dev libmpc-dev make file patch libelf-dev gettext bzip2 \
        flex bison ccache curl

    - name: Setup Python 2.7
      run: |
        echo "=== Setting up Python 2.7 ==="
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
        python --version

    - name: Install PS3 Toolchain (simplified)
      run: |
        echo "=== Installing PS3 toolchain ==="
        export PS3DEV=/usr/local/ps3dev
        sudo mkdir -p $PS3DEV
        sudo chown $USER:$USER $PS3DEV
        
        # Try a minimal toolchain setup first
        git clone --depth 1 https://github.com/ps3dev/ps3toolchain.git
        cd ps3toolchain
        
        # Run with timeout and better error handling
        timeout 45m ./toolchain.sh || {
          echo "Toolchain installation failed or timed out"
          echo "Checking for any log files..."
          find . -name "*.log" -exec tail -50 {} \;
          exit 1
        }

    - name: Install PSL1GHT
      run: |
        echo "=== Installing PSL1GHT ==="
        export PS3DEV=/usr/local/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin
        
        git clone --depth 1 https://github.com/ps3dev/PSL1GHT.git
        cd PSL1GHT
        make && sudo make install

    - name: Build Plugin
      run: |
        echo "=== Building the plugin ==="
        export PS3DEV=/usr/local/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin
        
        echo "Environment setup:"
        echo "PS3DEV=$PS3DEV"
        echo "PSL1GHT=$PSL1GHT"
        echo "PATH=$PATH"
        
        echo "Checking toolchain installation:"
        ls -la $PS3DEV/ || echo "PS3DEV directory not found"
        
        echo "Building plugin..."
        make clean || echo "Clean failed"
        make || echo "Build failed"
        
        echo "Checking build results:"
        ls -la *.sprx || echo "No .sprx files found"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ps3-plugin
        path: |
          guitar_remap.sprx
          guitar_remap.conf
