name: Build PS3 plugin
on:
  workflow_dispatch:
  push: { branches: [main, master] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build ps3dev image (Ubuntu-based)
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/ps3dev/ps3dev-docker.git
          tags: ps3dev:local
          load: true

      - name: Build plugin inside the image
        run: |
          mkdir -p build-out
          docker run --rm -v "$PWD:/src" -w /src ps3dev:local \
            bash -lc 'make -j1 && (cp -r build/* /src/build-out 2>/dev/null || true) && (cp -r *.sprx /src/build-out 2>/dev/null || true)'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps3-plugin-build
          path: build-out/**